# Basic Graph Thoery INSERTION & TRAVERSAL USING Dictionary

In [15]:
from collections import OrderedDict
from typing import Dict,List
class graphByMatrix:
    graph:Dict[int,List[int]]=OrderedDict()
    def matrixStore(self,x):
        for _ in range(x):
            x,y=map(int,input().split())
            if self.graph.__contains__(x):
                self.graph[x].append(y)
            else:
                self.graph[x]=[y]
    def matrixTraversal(self):
        print(self.graph)
        for i in self.graph:
            print(i,"=>",self.graph[i])

In [16]:
x=graphByMatrix()
r=int(input())
x.matrixStore(r)
x.matrixTraversal()

5
2 3
2 1
1 5
3 4
4 5
OrderedDict([(2, [3, 1]), (1, [5]), (3, [4]), (4, [5])])
2 => [3, 1]
1 => [5]
3 => [4]
4 => [5]


# Basic Graph Thoery INSERTION & TRAVERSAL USING Matrix

In [18]:
import numpy
i = int(input('Enter the number'))
a = numpy.zeros(shape=(i,i))
for _ in range(i):
    x,y=map(int,input().split())
    a[x][y]=1
print(a)

Enter the number5
0 2
2 1
2 4
4 1
1 3
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


# BFS TRAVERSAL

In [40]:
import numpy
from collections import deque
li=numpy.zeros(shape=(15))
key=list(x.graph.keys())
queue=deque()
queue.append(key[0])
while queue:
    temp=queue.popleft()
    if x.graph.__contains__(temp):
        queue.extend(x.graph[temp])
    if li[temp]==0:
        print(temp)
        li[temp]=1

2
3
1
4
5


# DFS TRAVERSAL